# app/models/schemas.py

from __future__ import annotations
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, List


class CallEvent(BaseModel):
    """
    Incoming event from Voice / Execution layer.
    This is the ONLY thing your Agentic OS trusts.
    """

    call_id: str = Field(
        ...,
        description="Globally unique call identifier generated by execution layer",
        min_length=1,
    )

    event_type: str = Field(
        ...,
        description="CALL_STARTED | CALL_ANSWERED | CALL_FAILED | CALL_COMPLETED",
        min_length=1,
    )

    # Optional but critical for healing decisions
    error_reason: Optional[str] = Field(
        default=None,
        description="NO_ANSWER | BUSY | SIP_TIMEOUT | AUDIO_LOSS | UNKNOWN",
    )

    latency_ms: Optional[int] = Field(
        default=None,
        description="End-to-end call setup latency if available",
        ge=0,
    )

    timestamp: Optional[int] = Field(
        default=None,
        description="Unix timestamp (seconds). If missing, server time is used.",
        ge=0,
    )

    # Voice quality signals
    rtp_loss: Optional[float] = Field(
        default=None,
        description="RTP packet loss percentage",
    )

    jitter: Optional[int] = Field(
        default=None,
        description="Jitter in milliseconds",
    )


class DecisionResponse(BaseModel):
    """
    Pure agentic decision.
    NO execution. NO SIP. NO Retell logic.
    """

    call_id: str

    decision: str = Field(
        ...,
        description="RETRY | STOP | SUCCESS | NO_ACTION",
    )

    reason: Optional[str] = Field(
        default=None,
        description="Why this decision was made",
    )

    retry_count: Optional[int] = Field(
        default=None,
        description="Current retry count after this decision",
        ge=0,
    )

    current_state: Optional[str] = Field(
        default=None,
        description="Current call lifecycle state",
    )

    # Advanced Day-3 fields
    action: Optional[str] = Field(
        default=None,
        description="Deterministic action to take",
    )

    cooldown: Optional[int] = Field(
        default=None,
        description="Cooldown time in seconds",
    )

    params: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Optional action parameters",
    )

    voice_quality: Optional[str] = Field(
        default=None,
        description="OK | POOR",
    )

    score: Optional[float] = Field(
        default=None,
        description="Quality score (0.0 to 1.0)",
    )

    sla_status: Optional[str] = Field(
        default=None,
        description="SLA_OK | SLA_BREACH",
    )

    violations: Optional[List[str]] = Field(
        default_factory=list,
        description="List of SLA violations",
    )

# Rebuild model to resolve any forward references or lazy types
DecisionResponse.model_rebuild()
