# app/core/constants.py

from __future__ import annotations

# ---- Call lifecycle states (Agentic OS state machine) ----
STATE_INIT = "INIT"
STATE_CONNECTING = "CONNECTING"
STATE_ACTIVE = "ACTIVE"
STATE_FAILED = "FAILED"
STATE_HEALED = "HEALED"
STATE_COMPLETED = "COMPLETED"

CALL_STATES = {
    STATE_INIT,
    STATE_CONNECTING,
    STATE_ACTIVE,
    STATE_FAILED,
    STATE_HEALED,
    STATE_COMPLETED,
}

# ---- Incoming event types (what Voice/Execution layer sends) ----
EVENT_CALL_STARTED = "CALL_STARTED"
EVENT_CALL_ANSWERED = "CALL_ANSWERED"
EVENT_CALL_FAILED = "CALL_FAILED"
EVENT_CALL_COMPLETED = "CALL_COMPLETED"

CALL_EVENTS = {
    EVENT_CALL_STARTED,
    EVENT_CALL_ANSWERED,
    EVENT_CALL_FAILED,
    EVENT_CALL_COMPLETED,
}

# ---- Decisions (what Agentic OS returns; no execution here) ----
DECISION_RETRY = "RETRY"
DECISION_STOP = "STOP"
DECISION_SUCCESS = "SUCCESS"
DECISION_NO_ACTION = "NO_ACTION"
DECISION_DELAY = "DELAY"
DECISION_REJECT = "REJECT"
DECISION_ALLOW_CALL = "ALLOW_CALL"

DECISIONS = {
    DECISION_RETRY,
    DECISION_STOP,
    DECISION_SUCCESS,
    DECISION_NO_ACTION,
    DECISION_DELAY,
    DECISION_REJECT,
    DECISION_ALLOW_CALL,
}

# ---- Healing Actions (deterministic outputs) ----
ACTION_RETRY_CALL = "RETRY_CALL"
ACTION_ESCALATE_TO_SMS = "ESCALATE_TO_SMS"
ACTION_REINVITE = "REINVITE"
ACTION_SWITCH_CODEC = "SWITCH_CODEC"
ACTION_ABORT_AND_LOG = "ABORT_AND_LOG"
ACTION_LOG_AND_STOP = "LOG_AND_STOP"

HEALING_ACTIONS = {
    ACTION_RETRY_CALL,
    ACTION_ESCALATE_TO_SMS,
    ACTION_REINVITE,
    ACTION_SWITCH_CODEC,
    ACTION_ABORT_AND_LOG,
    ACTION_LOG_AND_STOP,
}

# ---- Default mapping: event -> state (Orchestration agent uses this) ----
EVENT_TO_STATE = {
    EVENT_CALL_STARTED: STATE_CONNECTING,
    EVENT_CALL_ANSWERED: STATE_ACTIVE,
    EVENT_CALL_FAILED: STATE_FAILED,
    EVENT_CALL_COMPLETED: STATE_COMPLETED,
}

# ---- Error / failure reasons (telecom signals; expandable) ----
REASON_NO_ANSWER = "NO_ANSWER"
REASON_BUSY = "BUSY"
REASON_SIP_TIMEOUT = "SIP_TIMEOUT"
REASON_AUDIO_LOSS = "AUDIO_LOSS"
REASON_RTP_LOSS_HIGH = "RTP_LOSS_HIGH"
REASON_UNKNOWN = "UNKNOWN"

FAIL_REASONS = {
    REASON_NO_ANSWER,
    REASON_BUSY,
    REASON_SIP_TIMEOUT,
    REASON_AUDIO_LOSS,
    REASON_RTP_LOSS_HIGH,
    REASON_UNKNOWN,
}

# ---- SLA Status ----
SLA_OK = "SLA_OK"
SLA_BREACH = "SLA_BREACH"

# ---- Voice Quality ----
QUALITY_OK = "OK"
QUALITY_POOR = "POOR"

# ---- Load Control ----
LOAD_REASON_HIGH_LOAD = "HIGH_LOAD"
